# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JD-oBAjwAlEDCCYJEE4OfQ-_PSf7q1c8
"""

from textblob import TextBlob
from google.colab import files
uploaded = files.upload()
filename = list(uploaded.keys())[0]
with open(filename, 'r', encoding='utf=8') as file:
   text = file.read()

blob = TextBlob(text)
polarity = blob.sentiment.polarity

if polarity > 0:
  sentiment = "Positive"
elif polarity < 0:
  sentiment = "Negative"
else :
  sentiment = "Neutral"


print("Polarity: ",polarity)
print(f"sentiment: {sentiment}")